// Promise have 2 parameter : resolve = then ,reject = catch
// Run resolve or reject then stop

// const promise1 = new Promise((resolve,reject) => {
//     //resolve('hello word');
//     reject('hi');
// });

// promise1
//     .then(res => console.log(res))
//     .catch(err => console.log(`err: ${err}`))



